name: Atualizar Feeds RSS

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:        # Permite execução manual pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install requests lxml

      - name: Executar script para gerar feeds
        run: python gerar_feed.py

      - name: Commit e push dos feeds atualizados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add feed_voloch.xml feed_netvasco.xml
          git commit -m "Atualização automática dos feeds RSS" || echo "Sem alterações"
          git push
