name: Atualizar Feed RSS
on:
  schedule:
    - cron: "0 */6 * * *"  # Roda a cada 6 horas (ajuste conforme necessário)
  workflow_dispatch:  # Permite executar manualmente (em "Actions" no GitHub)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Instalar dependências
        run: pip install requests beautifulsoup4 feedgenerator
      - name: Executar script
        run: python gerar_rss.py
      - name: Fazer commit do feed atualizado
        run: |
          git config --global user.name "Seu Nome"
          git config --global user.email "seu@email.com"
          git add blog_voloch.xml
          git commit -m "Atualização automática do Feed RSS"
          git push
